[package]
name = "fern-core"
description = "Minecraft launcher orchestration for Fern"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
fern-download.workspace = true
fern-meta.workspace = true
md-5.workspace = true
pearl-core.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
